name: Build and Package
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # --------------------- 代码检出 ---------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # --------------------- 环境准备 ---------------------
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Initialize Vite project
        run: |
          # 强制非交互模式初始化项目
          npm create vite@latest . --yes --template vanilla
          npm install vite --save-dev
          # 验证项目结构
          ls -la
          cat package.json

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Create Vite CSS config
        run: |
          cat > vite.css.config.js <<'EOF'
          import { defineConfig } from 'vite';          
          export default defineConfig({
            build: {
              emptyOutDir: false, // 保留构建产物
              rollupOptions: {
                input: ['./static/css/main.css'],
                output: {
                  dir: 'dist',
                  assetFileNames: 'main.css'
                },
              },
            },
          });
          EOF
      - name: Create Vite JS config
        run: |
          cat > vite.js.config.js <<'EOF'
          import { defineConfig } from 'vite';
          export default defineConfig({
            build: {
              emptyOutDir: false,  // 保留构建产物
              rollupOptions: {
                input: [
                  './static/js/jsq.js',    // JS 入口文件
                ],
                output: {
                  //inlineDynamicImports: false,
                  format: 'iife',          // 仅适用于 JS 文件
                  dir: 'dist',             // 输出目录
                  // 控制资源文件名（CSS 文件）
                  entryFileNames: 'jsq.js'
                }
              }
            }
          });
          EOF
      - name: Verify config file
        run: |
          ls -al
          echo "生成配置文件内容："
          cat vite.css.config.js
          cat vite.js.config.js
          echo -e "\n配置文件路径："
          realpath vite.css.config.js
          realpath vite.js.config.js

      - name: Build JS and CSS
        run: |
          npx vite build --config vite.js.config.js
          npx vite build --config vite.css.config.js
     
      # --------------------- 文件合并 ---------------------
      - name: Create combined JS
        run: |
          mkdir -p dist
          cat static/js/config.js dist/jsq.js > dist/all.js
          ls -al
          cat dist/all.js



          
